merge: (#14) Repository areas 설계
Team-ComIT/koala pull request #15
Opened 2022-08-04 15:14 UTC by khcho0125

close #14

2022-08-04 15:56 UTC, softpeanut requested changes

2022-08-04 15:56 UTC, softpeanut commented on koala-domain/src/main/kotlin/comit/simsimpulyi/koala/global/annotation/Port.kt
> +annotation class Port {
이건 왜 만들으셨나요 ~

2022-08-04 15:56 UTC, softpeanut commented on koala-domain/src/main/kotlin/comit/simsimpulyi/koala/domain/user/service/UserPersistencePort.kt
> +interface UserPersistencePort {
포트가 왜 여기있나요.. application 계층에 있어야 합니다

2022-08-04 15:56 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/annotation/Adapter.kt
> +annotation class Adapter {
얘도 왜 만들었나요 ~

2022-08-04 15:56 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/UserPersistenceAdapter.kt
> +class UserPersistenceAdapter(private val repository: UserRepository) : UserPersistencePort {
줄바꿈이 불편해요..

2022-08-04 15:56 UTC, softpeanut commented
그리고 like 부분 빠졌습니당

2022-08-04 16:09 UTC, khcho0125 commented
아직 다 안했어요.. 😵‍💫

2022-08-04 16:10 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/annotation/Adapter.kt
> +annotation class Adapter {
어댑터로 bean 등록할 생각으로 만들었어요

2022-08-04 16:11 UTC, khcho0125 commented on koala-domain/src/main/kotlin/comit/simsimpulyi/koala/global/annotation/Port.kt
> +annotation class Port {
이것도 componetscan 할생각으로 만들었어요

2022-08-05 02:25 UTC, softpeanut commented on koala-domain/src/main/kotlin/comit/simsimpulyi/koala/global/annotation/Port.kt
> +annotation class Port {
포트를 왜 굳이 스캔해서 만드나요?

2022-08-05 02:27 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/annotation/Adapter.kt
> +annotation class Adapter {
네이밍 컨벤션 정할 때 Adapter와 Port는 하지 않기로 했었는데..

2022-08-05 02:54 UTC, softpeanut commented on koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/feed/spi/FeedPersistencePort.kt
> +interface FeedPersistencePort {
혹시 저희 코드 컨벤션이 기억이 안나는지... 저희 Save와 Query 분리시키고 하나의 인터페이스로 통합하기로 했습니다

2022-08-05 02:54 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/mapper/FeedMapper.kt
> +class FeedMapper {
매퍼가 이게 끝인가요..?

2022-08-05 02:56 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/mapper/FeedMapper.kt
> +class FeedMapper {
아직 구현 중 입니다

2022-08-05 02:58 UTC, khcho0125 commented on koala-application/src/main/kotlin/comit/simsimpulyi/koala/domain/feed/spi/FeedPersistencePort.kt
> +interface FeedPersistencePort {
Adapter만 보고 Port 부분을 못봤네요..

2022-08-05 05:28 UTC, softpeanut submitted a review, later dismissed

2022-08-05 05:28 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/mapper/FeedMapper.kt
> +    fun toEntity(model: Feed, writer: UserEntity): FeedEntity
override 키워드 빠졌어요
그리고 writer는 뭐죠...? 엔티티로 변환하는 작업에서 다른 엔티티를 인자로 받으면..

2022-08-05 05:28 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/mapper/UserMapper.kt
> +interface UserMapper : BaseMapper<UserEntity, User> {
이건 다 구현이 안된 것 같은데...

2022-08-05 05:31 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/mapper/UserMapper.kt
> +interface UserMapper : BaseMapper<UserEntity, User> {
구현된 겁니다.

2022-08-05 05:37 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/mapper/FeedMapper.kt
> +    fun toEntity(model: Feed, writer: UserEntity): FeedEntity
인자의 갯수가 달라서 override가 빠졌습니다.

Feed model이 엔티티로 변환하기 위해서 작성자 엔티티가 필요한데
Feed model 처리하는 방법이 두 가지 있습니다.

1.  Mapper로 변환하면서 User Entity 호출

2. Mapper 호출 이전 User Entity 입력

1번의 경우에는 Mapper에 UserRepository를 import 해야합니다.

2번의 경우는 Mapper에 영향을 끼치지 않으면서 Application 단에서 충분히 처리할 수 있을 것이라 생각했기 때문에
2번의 경우를 고르게되었습니다.

2022-08-05 05:44 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/mapper/FeedMapper.kt
> +    fun toEntity(model: Feed, writer: UserEntity): FeedEntity
그런데 말입니다요... Application 단에서는 아쉽게도 UserEntity를 사용할 수 없습니다.
더군다가 UserRepository를 호출하는 것이 아닌 port를 통해 호출하는 것입니다...

2022-08-05 05:46 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/mapper/FeedMapper.kt
> +    fun toEntity(model: Feed, writer: UserEntity): FeedEntity
핵심은 매퍼에 영향을 끼치지 않도록 하는 것이 아니라 application과 infrastructure의 의존성을 분리하는 것입니다

2022-08-05 05:49 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/mapper/FeedMapper.kt
> +    fun toEntity(model: Feed, writer: UserEntity): FeedEntity
아아 Application 단이 아니라 Infrastructure 단인데 Feed 부분에서 UserEntity를 불러올 수는 없나요

2022-08-05 05:54 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/mapper/FeedMapper.kt
> +    fun toEntity(model: Feed, writer: UserEntity): FeedEntity
그럼 매번 똑같은 변환 작업에 UserEntity를 그때마다 호출하게 되지 않을까요

2022-08-05 05:54 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/mapper/FeedMapper.kt
> +    fun toEntity(model: Feed, writer: UserEntity): FeedEntity
두 방법 모두 다른 layer 영역에 침범하지는 않는데 변환 전에 받아오는 게 더 나은 방법이라고 생각했습니다.

2022-08-05 05:58 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/mapper/FeedMapper.kt
> +    fun toEntity(model: Feed, writer: UserEntity): FeedEntity
만약 UserEntity를 가져오지 않는다면 본래 Feed Entity의 writer가 손상되지 않도록 해야 될 것으로 보입니다...

2022-08-05 06:00 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/mapper/FeedMapper.kt
> +    fun toEntity(model: Feed, writer: UserEntity): FeedEntity
왜죠? Mapper를 호출하는 측에서 UserEntity를 넘기게 된다면 UserPersistenceAdapter를 통해 UserEntity를 호출할 때마다 조회하는 로직을 짜게 되는데 동일 코드 중복이 너무 중복하게 될 것 같습니다. 그리고 실수가 발생할 수도 있고 호출하는 입장은 단순히 Feed 도메인을 FeedEntity로 변환하고 싶을 뿐인데 그때마다 UserEntity를 조회해야 한다면 불편할 것 같아요

2022-08-05 06:05 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/mapper/FeedMapper.kt
> +    fun toEntity(model: Feed, writer: UserEntity): FeedEntity
그러면 writer 필드를 Null로 두는 수 밖에 없는데 @DynamicUpdate 같이 변경된 부분만 값을 변경해주는 방식으로 진행해야 합니다...

2022-08-05 06:06 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/feed/mapper/FeedMapper.kt
> +    fun toEntity(model: Feed, writer: UserEntity): FeedEntity
그렇네요 코드 중복은 생각 못했습니다...

2022-08-05 07:47 UTC, softpeanut approved these changes

2022-08-05 08:26 UTC, merged