merge: (#18) Security 설계하기
Team-ComIT/koala pull request #20
Opened 2022-08-11 06:02 UTC by khcho0125

close #18

2022-08-12 11:18 UTC, softpeanut requested changes

2022-08-12 11:18 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/filter/FilterConfig.kt
> +        builder.addFilter(JwtFilter(jwtAdapter))
add filter 보다는.. usernameauthenticationfilter 전에 추가해야 할 것 같네요

2022-08-12 11:18 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/SecurityConfig.kt
> +@EnableWebSecurity
이거 필요 없지 않나요?
spring security 5.7.x 버전으로 공식 홈페이지 보고 버전에 따라 맞춰주시면 좋을 것 같아여

2022-08-12 11:18 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/SecurityProperties.kt
> +    val secret = Base64.getEncoder().encodeToString(secret.padStart(64).toByteArray())!!
secretkey가 좋을 것 같아요
혹시 padStart를 하신 이유가 무엇일까요

2022-08-12 11:18 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtAdapter.kt
> +    override fun generateAccessToken(userId: UUID, authority: Authority): String {
userId를 토큰의 subject로 넣으시는 이유가 있을까요?
제가 생각하기에 userId를 그대로 이용하다보면 pk가 그대로 노출되는 거고 결코 안전하지 않기 때문에 email이나 accountid와 같은 별도의 유일한 값을 이용하면 좋을 것 같습니다

2022-08-12 11:18 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtAdapter.kt
> +    fun generateToken(userId: UUID, authority: Authority, exp: Int, type: String): String {
해당 메서드는 private 접근 제어자로 외부 접근을 막아야 할 것 같아요

2022-08-12 11:18 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtAdapter.kt
> +    }
제가 생각하기에 해당 메서드 들은 JwtAdapter가 상속받고 있는 ReceiveTokenPort와 전혀 연관되지 않은 메서드 같은데 하나의 클래스에 넣기에는 단일 책임 원칙을 위반하는 것 같습니다

2022-08-12 11:18 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/UserPersistenceAdapter.kt
> +    fun findUserEntityById(userId: UUID): UserEntity? {
해당 메서드를 새로 만든 이유가 뭐죠..?

2022-08-12 11:18 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/principle/AuthDetails.kt
> +    }
해당 메서드들의 반환값이 false인 이유가 뭐죠..?
오히려 true여야 할 것 같습니다

2022-08-12 11:32 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/SecurityProperties.kt
> +    val secret = Base64.getEncoder().encodeToString(secret.padStart(64).toByteArray())!!
혹시라도 secertkey 잘못된 입력이 들어갔을 때 문제없게 pading했습니다.

2022-08-12 11:33 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtAdapter.kt
> +    override fun generateAccessToken(userId: UUID, authority: Authority): String {
알겠습니다. email로 교체하도록 할게요.

2022-08-12 11:35 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/UserPersistenceAdapter.kt
> +    fun findUserEntityById(userId: UUID): UserEntity? {
이 메서드가 jwt 회원 정보를 가져올 때 사용되는데 해당 영역에서 발생되는 Exception이 queryUserEntityById와 차이가 있다고 생각되어서 새로 만들었습니다.

2022-08-12 13:39 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/SecurityProperties.kt
> +    val secret = Base64.getEncoder().encodeToString(secret.padStart(64).toByteArray())!!
혹시 64글자로 채워야하는 이유가 있나요?

2022-08-12 13:40 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/UserPersistenceAdapter.kt
> +    fun findUserEntityById(userId: UUID): UserEntity? {
그러면 userdetailsservice에서만 직접 repository를 호출하는 것은 어떤가요?

2022-08-12 14:03 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/SecurityProperties.kt
> +    val secret = Base64.getEncoder().encodeToString(secret.padStart(64).toByteArray())!!
Token 알고리즘이 HS512가 쓰였기 때문에 64글자 미만이면 작동하지 않는 걸로 알고 있습니다.

2022-08-12 14:06 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/UserPersistenceAdapter.kt
> +    fun findUserEntityById(userId: UUID): UserEntity? {
그러는게 좋긴한데 Adapter를 통해서 접근하지 않는게 문제될지 모르겠어서..
그냥 Adapter로 해놨었어요

2022-08-13 12:28 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/filter/FilterConfig.kt
> +) : AbstractHttpConfigurer<FilterConfig, HttpSecurity>() {
해당 코드를 SecurityConfigurerAdapter를 이용한 코드로 변경하는 것이 더 확장성이 좋아보입니다

2022-08-13 12:28 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/SecurityConfig.kt
> +            .build()
해당 코드를 구간별로 .으로 구분하는 대신 별도로 나누는 건 어떤가요?

2022-08-13 12:28 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/FilterTokenAdapter.kt
> +class FilterTokenAdapter(
이 클래스는 내부 비즈니스 영역과 교류가 없기 때문에 Adapter 보다 다른 이름이 좋을 것 같습니다

2022-08-13 12:28 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtAdapter.kt
> +class JwtAdapter(
일반적인 JwtAdapter보다 토큰을 생산하는 느낌이 들어가면 좋을 것 같아요

2022-08-13 12:28 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/FilterTokenAdapter.kt
> +        if(bearer.isNotEmpty().and(bearer.startsWith("bearer "))) {
Authentication과 Bearer는 상수로 표현하는 것이 어떤가여

2022-08-13 12:28 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/FilterTokenAdapter.kt
> +        if(claims.header[Header.JWT_TYPE] != "access") throw Exception() // TODO
음... 해당 로직이 있으면 refresh token일 경우 무조건 예외가 발생할 것 같은데.. 그렇게 되면 안되지 않나요?

2022-08-13 12:28 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/persistence/user/UserPersistenceAdapter.kt
> +    fun findUserEntityById(userId: UUID): UserEntity? {
사실 UserPersistenceAdapter를 비롯한 모든 인바운드, 아웃바운드 어댑터들은 내부 비즈니스 영역과의 교류를 위해 존재하는 것이기 때문에 이외에 다른 로직에서 한정적으로 사용하는 경우에 대해서는 영속성 repository를 사용해도 괜찮을 것 같습니다

2022-08-14 03:08 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/FilterTokenAdapter.kt
> +        if(claims.header[Header.JWT_TYPE] != "access") throw Exception() // TODO
access token을 통해서만 자원에 접근 가능하기 때문에 refresh token일 경우 의도적으로 예외가 발생하도록 만든 겁니다.

2022-08-14 03:41 UTC, khcho0125 commented
refresh token에 사용자 정보를 넣지 않는 게 좋대서 token 생성 함수를 각자 만드는 게 어떨까 생각합니다.

2022-08-14 03:57 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/FilterTokenAdapter.kt
> +class FilterTokenAdapter(
FilterTokenAdapter → JwtInterpreter

2022-08-14 03:58 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtAdapter.kt
> +class JwtAdapter(
JwtAdapter → JwtGenerator

2022-08-14 14:41 UTC, softpeanut commented
> refresh token에 사용자 정보를 넣지 않는 게 좋대서 token 생성 함수를 각자 만드는 게 어떨까 생각합니다.

좋은 생각인 것 같습니다 저는 리프레시 토큰에 사용자 정보를 넣어서 예외를 발생하면 안된다고 생각해서 코멘트를 달았었는데 생성 함수를 각자 만들면 예외 발생시키는 게 맞는 것 같습니다

2022-08-14 14:54 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/SecurityConfig.kt
> +            .sessionManagement()
세션 정책도 구분하면 좋을 것 같아요

2022-08-14 14:54 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtComponent.kt
> +    const val JWT_PREFIX = "bearer "
해당 prefix는 Bearer 아닌가요..?

2022-08-14 14:54 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtGenerator.kt
> +class JwtGenerator(
요건 ~~Adapter가 되어야 할 것 같은데 JwtAdapter보다 GenerateJwtAdapter는 어떤가요?

2022-08-14 14:54 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtInterpreter.kt
> +    }
해당 코드는 JwtFilter로 이동하는 거 어떻게 생각하시나요?

2022-08-14 14:54 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtInterpreter.kt
> +            .parseClaimsJws(token)
Expired와 Invalid와 같이 토큰과 관련된 예외에 대한 핸들링은 따로 없는 건가요?

2022-08-14 14:54 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtInterpreter.kt
> +class JwtInterpreter(
이건... JwtParser 같은 느낌은 어떠신지

2022-08-14 14:55 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtComponent.kt
> +    const val JWT_PREFIX = "bearer "
대문자네..ㅎㅎ

2022-08-14 15:03 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtInterpreter.kt
> +            .parseClaimsJws(token)
예외를 직접 못 만들어서 망설였네요..

2022-08-14 15:24 UTC, khcho0125 commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtInterpreter.kt
> +    }
해당 코드가 'Jwt' 주제를 중심으로 두고 있습니다. JwtFilter가 사실 TokenFilter 이라 할 수 있으니
'Jwt' 주제에 더 가까운 JwtParser에 두는 게 더 좋아 보입니다.
'Jwt' 부분에 변경이 있을 경우에도 같이 교체되어야 하는 코드이므로 Parser에 두는 게 맞다는 생각입니다.

2022-08-14 16:18 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtInterpreter.kt
> +    }
제 생각엔 해당 메서드는 jwt 토큰을 HttpServletRequest에서 꺼내오는 것이 아니라 request header로부터 원하는 값을 가져오고 알맞은 형식으로 가공하는 것이기 때문에 jwt에 중점되어 있는 JwtParser보다 TokenFilter 역할을 하는 JwtFilter에 있는 것이 적합해 보입니다

2022-08-14 16:20 UTC, softpeanut commented on koala-infrastructure/src/main/kotlin/comit/simsimpulyi/koala/global/security/token/JwtInterpreter.kt
> +    }
jwt와 관련된 의존성도, 사용하는 라이브러리도 없기 때문에 더욱 JwtFilter로 이동하고, JwtFilter의 이름을 TokenFilter로 수정하는 것이 좋을 것 같습니다

2022-08-15 03:07 UTC, softpeanut approved these changes

2022-08-15 03:31 UTC, merged